# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.cache/wt [current_project]
set_property parent.project_path C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/three_MUX.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/micro_store.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/microPC.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/ins_register.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/incrementer.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/decoder.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/microCU_top.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/LUT.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/reg_file.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/ClkDiv.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/sevseg.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/new/ins_module.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/new/Top.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/new/gen_reg.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/new/ins_reg.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/new/datapath_top.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/new/adr_MUX.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/new/gen_MUX.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/new/shifter.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/new/sign_ext.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/new/alu_control.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/imports/ALU/Three_One_MUX.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/imports/bit_binary_logic_VHDL/logic_unit.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/new/ALU_Structural.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/new/ALU_Structural32.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/new/Arithmetic_Unit.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/new/OVF_Structural.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/imports/sources_1/new/FullAdder.vhd
  C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/sources_1/new/periph_reg.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/constrs_1/imports/Lab6.srcs/lab5_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/owend/Downloads/CPU_Complete/CPU_Complete/CPU_Complete.srcs/constrs_1/imports/Lab6.srcs/lab5_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
